spring:
  application:
    name: config-client
  cloud:
    config:
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8882
management:
  endpoints:
    web:
      exposure:
        include: '*'