eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-lucy
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#http://localhost:8762/hystrix/
#http://localhost:8762/actuator/hystrix.stream